baseurl: "http://ghui.me/"
title: "ByGhui"        
publishdir: "/Users/ghui/.hugo_blog"        
watch: true
metaDataFormat: "yaml"
Taxonomies:
  tag: "tags"
  category: "categories"
permalinks:
    post: post/:year/:month/:slug/
params:
    author: "ghui"
    Subtitle: "sharing,improving"