baseurl: "http://ghui.me/"
title: "ByGhui"        
publishdir: "/Users/ghui/.hugo_blog"        
watch: true
metaDataFormat: "yaml"
menu:
	main:
      - Name: "归档"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
      - Name: "关于我"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "about"
        Weight: -100
        URL: "/about/"
Taxonomies:
  tag: "tags"
  category: "categories"
permalinks:
    post: post/:year/:month/:slug/
params:
    author: "ghui"
    Subtitle: "sharing,improving" 
    Categories:
    - "读书笔记"
    - "技术文章"
    - "思考感悟"       
blackfriday:
	fractions: true