baseurl = "http://ghui.me/"
languageCode = "zh-CN"
title = "ByGhui"
publishdir = "/Users/ghui/.hugo_blog"
[params]
  author = "ghui"
  Subtitle = "sharing,improving"
  Summary = false
  Content = false
