baseurl = "http://ghuiii.github.io/"
languageCode = "en-us"
title = "ByGhui"
publishdir = "/Users/ghui/.hugo_blog"
[params]
  author = "ghui"
  Subtitle = "sharing,improving"
  Summary = false
  Content = false
