baseurl: "http://ghui.me"
title: "ghui's Blog"        
publishdir: "/Users/ghui/.hugo_blog"        
watch: true
metaDataFormat: "yaml"
disqusShortname:  "ghui"
permalinks:
    post: post/:year/:month/:filename
Taxonomies:
  tag: "tags"
  category: "categories"
params:
  author: "ghui"
  Subtitle: "sharing,improving"
menu:
  main:
      - Name: "Dev"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "dev"
        URL: "/categories/dev"
      - Name: "Feeling"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        Identifier: "FeelingWu"
        URL: "/categories/feeling"
      - Name: "Others"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        Identifier: "others"
        URL: "/categories/others"
