#!/bin/bash
echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"
cd ~/ghui.me
# Build the project.
# if using a theme, replace by `hugo -t <yourtheme>`
hugo

# Go To Public folder
cd /Users/ghui/.hugo_blog
# Add changes to git.
git co .
git clean -df
git add -A

# Commit changes.
msg="rebuilding site `date`"
if [ $# -eq 1 ]
	  then msg="$1"
	  fi
	  git commit -m "$msg"

	  # Push output to server
	  git push origin master

	  # Come Back
	  cd ~/ghui.me
          echo -e "\033[0;32mDeploying source to GitHub...\033[0m"
	  git add -A
	  git commit -m "$msg"
	  git push origin master

